name: Ofoq Video Renderer (Final Fix)

on:
  workflow_dispatch:
    inputs:
      js_code:
        description: 'JS Code'
        required: true

jobs:
  build-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install
        run: |
          npm install playwright
          npx playwright install chromium
          sudo apt-get install -y xvfb

      - name: Render
        env:
          USER_CODE: ${{ github.event.inputs.js_code }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" node render_script.js

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Video_Result
          path: output.mp4
