name: Ofoq Video Renderer

on:
  workflow_dispatch:
    inputs:
      js_code:
        description: 'JS Code to execute'
        required: true

jobs:
  build-video:
    runs-on: ubuntu-latest
    steps:
      # تحديث إلى v4
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # تحديث النسخة لضمان الأداء
          
      - name: Install Dependencies
        run: |
          npm install playwright ffmpeg-static
          npx playwright install chromium

      - name: Render Video
        env:
          USER_CODE: ${{ github.event.inputs.js_code }}
        run: node render_script.js

      # التغيير الجوهري هنا: التحديث إلى v4
      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: Rendered_Video_${{ github.run_id }} # إضافة ID تجنباً لتكرار الأسماء
          path: output.mp4
          retention-days: 1 # لحذف الملف تلقائياً بعد يوم وتوفير المساحة
